# Generated by Django 4.0.1 on 2022-01-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('country', models.CharField(max_length=8, verbose_name='Country ISO')),
                ('dat', models.DateTimeField(verbose_name='Date and time')),
                ('icon', models.CharField(default='04d', max_length=10, verbose_name='Icon')),
                ('wind', models.FloatField(verbose_name='Wind speed')),
                ('visibility', models.IntegerField(verbose_name='Visibility')),
                ('temp', models.FloatField(verbose_name='Temperature')),
                ('feels_like', models.FloatField(verbose_name='Feels like')),
                ('humidity', models.IntegerField(verbose_name='Humidity')),
                ('pressure', models.IntegerField(verbose_name='Pressure')),
            ],
        ),
    ]
